apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
  labels:
    app: dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
      - name: dispatcher
        image: public.ecr.aws/h1k5r6g8/aliahmedkhan/generic_repo:ml-workload-v0.4
        # imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: "redis.default.svc.cluster.local"
        - name: INFERENCE_URL
          value: "http://ml-workload.default.svc.cluster.local:6000/predict"
        command:
        - sh
        - -c
        - |
          chmod +x /app/entrypoint/dispatcher-entrypoint.sh \
            && exec /app/entrypoint/dispatcher-entrypoint.sh
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: vol
          mountPath: /app/test_images
          subPath: app/test_images-2/imagenet-sample-images   # Removed leading slash
        - name: vol
          mountPath: /app/entrypoint/
          subPath: app/test_images-2/  # Removed leading slash
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: myclaim2


---
apiVersion: v1
kind: Service
metadata:
  name: dispatcher
  labels:
    app: dispatcher
spec:
  type: ClusterIP
  ports:
  - port: 7000
    targetPort: 7000
    protocol: TCP
    name: dispatcher
  selector:
    app: dispatcher