apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-workload
  labels:
    app: ml-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-workload
  template:
    metadata:
      labels:
        app: ml-workload
    spec:
      containers:
      - name: ml-workload
        image: public.ecr.aws/h1k5r6g8/aliahmedkhan/generic_repo:ml-workload-v0.4
        # imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          chmod +x /app/entrypoint/entrypoint.sh \
            && exec /app/entrypoint/entrypoint.sh
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: vol
          mountPath: /app/test_images
          subPath: app/test_images-2/imagenet-sample-images   # Removed leading slash
        - name: vol
          mountPath: /app/entrypoint/
          subPath: app/test_images-2/  # Removed leading slash
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: myclaim2

---
apiVersion: v1
kind: Service
metadata:
  name: ml-workload
  labels:
    app: ml-workload
spec:
  type: ClusterIP
  ports:
  - port: 6000
    targetPort: 6000
    protocol: TCP
    name: ml-workload
  selector:
    app: ml-workload